version: 2  # required for PY39+
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - "graphviz"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - create

sphinx:
  configuration: docs/source/conf.py
